- name: Include OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family | lower }}.yml"

- name: Install yum packages | swift node
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ yum_node_packages }}"
  when: "'swift_storage_node' in group_names"

- name: Install yum packages | swift controller
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ yum_controller_packages }}"
  when: "'swift_server' in group_names"


